version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: second_brain_timescaledb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=second_brain
    ports:
      - "5435:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]